# Default values for atm-layer-reporting-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: 00000000000.dkr.ecr.eu-south-1.amazonaws.com/xxxxxxx
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: latest

namespace: pagopa

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

secretProviderClass:
  enabled: false
  name: atm-layer-reporting-service-secrets
  env: dev

# milBasePath: https://mil-u-apim.azure-api.net

database:
  type: postgresql
  jdbc_url: jdbc:postgresql://pagopa-dev-atm-layer-rds.cluster-cyezwzpjc2tj.eu-south-1.rds.amazonaws.com:5431/pagopadb?currentSchema=atm_layer_reporting_schema
  reactive_url: postgresql://pagopa-dev-atm-layer-rds.cluster-cyezwzpjc2tj.eu-south-1.rds.amazonaws.com:5431/pagopadb?currentSchema=atm_layer_reporting_schema
  db_name: pagopadb
  credentialsSecretEnabled: true
  credentialsSecretName: "pagopa-dev-atm-layer-model-database"
  credentialsSecretKeys:
    username: USERNAME_DB
    password: PASSWORD_DB

# tracing:
#   enabled: "false"
#   endpointBasePath: "http://jaeger-collector.default.svc.cluster.local:4317"
#   enableJDBCMonitoring: "true"

# reportingService:
#   environment: dev
#   executionMode: READ_WRITE
#   logLevel: INFO
#   applicationBasePath: /api/v1/reporting-service
#   swaggerPath: /swagger-ui
#   healthPath: /health/v1/reporting-service
#   openapiPath: /health/v1/reporting-service

# milAuth:
#   clientCredentials: client_credentials
#   credentialsSecretEnabled: true
#   credentialsSecretName: "pagopa-dev-atm-layer-reporting-service-mil-auth"
#   credentialsSecretKeys:
#     clientId: CLIENT_ID
#     clientSecret: CLIENT_SECRET

# apiGatewayId: 8o3pf45im8
# cognitoUserPoolId: eu-south-1_sEZF9PqAf
# cognitoScopes: dev/tasks


serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::00000000000:role/pagopa-dev-atm-layer-xxxxxx-serviceaccount-role
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: pagopa-dev-atm-layer-reporting-service

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

deployment:
  name: pagopa-dev-atm-layer-reporting-service
  annotations:
    reloader.stakater.com/auto: "true"

service:
  name: pagopa-dev-atm-layer-reporting-service
  type: NodePort
  port: 8080

ingress:
  enabled: true
  name: pagopa-dev-atm-layer-reporting-service
  className: ""
  annotations: 
    kubernetes.io/ingress.class: "alb"
    alb.ingress.kubernetes.io/scheme: "internal"
    alb.ingress.kubernetes.io/group.name: "alb-controller"
    alb.ingress.kubernetes.io/load-balancer-name: "pagopa-dev-atm-layer-alb-int"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTP": 8080}]'
  hosts:
    - host:
      paths:
        - path: /api/v1/transfer-lists
          pathType: Prefix
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 600m
    memory: 600Mi
  requests:
    cpu: 300m
    memory: 300Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

Release:
  Time:
    Seconds: 60
